name: Auto Assign PR to Author and Add Reviewers

on:
  pull_request:
    types: [opened, reopened]

permissions:
  pull-requests: write

jobs:
  assign-and-review:
    runs-on: ubuntu-latest
    steps:
      - name: Assign PR to author
        uses: toshimaru/auto-author-assign@v3.0.1

      - name: Request team review
        uses: rowi1de/auto-assign-review-teams@v1.1.3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          org: "motif-ui" #only needed for  pick-one-from-persons-or-team=true
          teams: "core-team" # only works for GitHub Organisation/Teams
          include-draft: false # Draft PRs will be skipped (default: false)