name: NPM Release
on:
  workflow_dispatch:

jobs:

  guard:
    runs-on: ubuntu-latest
    steps:
      - name: Allow only main branch
        run: |
          if [ "${GITHUB_REF_NAME}" != "main" ]; then
            echo "âŒ This workflow can only be run on main branch."
            exit 1
          fi
  ###########################
  ######## release ##########
  ###########################
  release:
    name: Release
    runs-on: ubuntu-latest
    environment: release

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      HUSKY: 0
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup-node-deps

      - name: Prepare npmrc for npm publish
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc

      - name: Semantic Release
        run: npx semantic-release
